version: "3.8"
services:
  klarna-api-test-app:
    image: xamien/klarna-api-integration-test:0.1.0
    build: ./
    restart: always
    environment:
      DEBUG: klarna*
      KLARNA_API_USERNAME: xxx
      KLARNA_API_PASSWORD: xxx
    ports:
      - 3000:3000
